"""add col token encr

Revision ID: 63911955e809
Revises: 2919267f9617
Create Date: 2026-01-03 19:27:06.739914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "63911955e809"
down_revision: Union[str, None] = "2919267f9617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bots",
        sa.Column("token_encrypted", sa.String(length=1000), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "token_encrypted")
    # ### end Alembic commands ###
